// Libraries
import 'package:flutter/material.dart';

class Recipe {
  // Variables
  int id;
  String title;
  String description;
  String image;
  String cuisine;
  String videoLink;
  String totalTime;
  bool isFavorited;
  int serves;
  int calories;
  int carbo;
  int protein;
  String ingredients;

  Recipe(
      this.id,
      this.title,
      this.description,
      this.image,
      this.cuisine,
      this.videoLink,
      this.totalTime,
      this.isFavorited,
      this.serves,
      this.calories,
      this.carbo,
      this.protein,
      this.ingredients);
}

List<Recipe> getRecipes() {
  return <Recipe>[
    Recipe(
        0,
        "Chicken Fried Rice",
        "So irresistibly delicious",
        "assets/images/chicken_fried_rice.png",
        "American",
        "https://www.youtube.com/watch?v=R57hSkeVNG8",
        "40 Minutes",
        false,
        4,
        250,
        35,
        6,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    Recipe(
        1,
        "Pasta Bolognese",
        "True Italian classic with a meaty, chilli sauce",
        "assets/images/pasta_bolognese.png",
        "Italian",
        "",
        "20 Minutes",
        false,
        4,
        200,
        45,
        10,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    Recipe(
        2,
        "Garlic Potatoes",
        "Crispy Garlic Roasted Potatoes",
        "assets/images/filete_con_papas_cambray.png",
        "Indian",
        "",
        "25 Minutes",
        false,
        4,
        150,
        30,
        8,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    Recipe(
        3,
        "Asparagus",
        "White Onion, Fennel, and watercress Salad",
        "assets/images/asparagus.png",
        "American",
        "",
        "30 Minutes",
        true,
        4,
        190,
        35,
        12,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    Recipe(
        4,
        "Filet Mignon",
        "Bacon-Wrapped Filet Mignon",
        "assets/images/steak_bacon.png",
        "Japan",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "35 Minutes",
        false,
        4,
        250,
        55,
        20,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    Recipe(
        5,
        "Hamburger",
        "Hamburger",
        "assets/images/hamburger2.png",
        "American",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "35 Minutes",
        false,
        4,
        250,
        55,
        20,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Burger & Chips
    Recipe(
        6,
        "Burger & Chips",
        "Sooo Good!",
        "assets/images/hamburger3.png",
        "Global",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "1 hrs 20 mins",
        false,
        4,
        679,
        83,
        55,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Fish & Chips
    Recipe(
        7,
        "Fish & Chips",
        "Sooo Good!",
        "assets/images/fishandchips.png",
        "American",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "35 Minutes",
        false,
        4,
        250,
        55,
        20,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Sandwich
    Recipe(
        8,
        "Sandwich",
        "Sooo Good!",
        "assets/images/sandwich.png",
        "American",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "35 Minutes",
        false,
        4,
        250,
        55,
        20,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Pizza
    Recipe(
        9,
        "Pizza",
        "This homemade pizza recipe is perfect for parties! Everyone loves pizza, and your guests can customize their toppings to suit their personal tastes.",
        "assets/images/pizza.png",
        "Italian",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "1 hrs 20 mins",
        false,
        8,
        481,
        55,
        20,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Roast Dinner
    Recipe(
        10,
        "Roast Dinner",
        "Sooo Good!",
        "assets/images/roastdinner.png",
        "American",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "35 Minutes",
        false,
        4,
        250,
        98,
        18,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Cooked Breakfast
    Recipe(
        11,
        "Cooked Breakfast",
        "Bacon, sausages, eggs, tomatoes, mushrooms, toast, and beans all on one plate: is a Full English breakfast the most ultimate breakfast ever?",
        "assets/images/englishbreakfast.png",
        "English",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "30 Minutes",
        false,
        1,
        360,
        27,
        25,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Lasagne
    Recipe(
        12,
        "Lasagne",
        "It takes a little work, but it is worth it.",
        "assets/images/lasagne.png",
        "Italian",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "3 hrs 15 mins",
        false,
        12,
        448,
        37,
        30,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Pie & Mash
    Recipe(
        13,
        "Pie & Mash",
        "Sooo Good!",
        "assets/images/pieandmash.png",
        "English",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "35 Minutes",
        false,
        2,
        250,
        55,
        20,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Jacket potato
    Recipe(
        14,
        "Jacket Potato",
        "Bake a potato perfectly every time! With the olive oil & sea salt coating, it'll come out of the oven with crispy skin and fluffy insides that are delicious with your favorite toppings.",
        "assets/images/jacketpotato.png",
        "English",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "60 Minutes",
        false,
        4,
        419,
        38,
        13,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Chicken korma
    Recipe(
        15,
        "Chicken Korma",
        "Chicken Korma is a traditional Indian dish that’s light and flavorful almond curry made with tomato paste, plenty of spices and cream thats buttery and completely delicious.",
        "assets/images/creamycurry.png",
        "Indian",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "45 Minutes",
        false,
        4,
        682,
        11,
        36,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Salad with dressing
    Recipe(
        16,
        "Salad with Dressing",
        "Sooo Good!",
        "assets/images/saladwithdressing.png",
        "Italian",
        "https://www.youtube.com/watch?v=_WN-YFwKj7w",
        "35 Minutes",
        false,
        4,
        250,
        55,
        20,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
    // Cottage pie
    Recipe(
        17,
        "Cottage Pie",
        "Cottage pie, a traditional British dish, is comforting and utterly delicious! This is an easy recipe to make, affordable and freezes beautifully! Comfort food at its best!",
        "assets/images/cottagepie.png",
        "English",
        "https://www.youtube.com/watch?v=B8QZCbyDg-4",
        "55 mins",
        false,
        4,
        440,
        40,
        29,
        "2 cups pecans, divided \n1 tablespoon unsalted butter, melted \n1/4 teaspoon kosher salt, plus more \n3 tablespoons fresh lemon juice \n2 tablespoons olive oil \n1/2 teaspoon honey"),
  ];
}
